from reportlab.lib import styles
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph


def generate_pdf_report(
    filename,
    best_role,
    detected_skills,
    missing_skills,
    ats_score,
    career,
    roadmap,
    review
):
    """
    Generates a Resume Analysis PDF Report.
    """

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ==========================
    # Title
    # ==========================

    story.append(
        Paragraph("<b>SkillPilot AI Resume Report</b>", styles["Title"])
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    # ==========================
    # Career Information
    # ==========================

    story.append(
        Paragraph("<b>Career Analysis</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"Best Role : {best_role['Role']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"Match Score : {best_role['Score']}%", styles["Normal"])
    )

    story.append(
        Paragraph(f"ATS Score : {ats_score}/100", styles["Normal"])
    )

    story.append(
        Paragraph(
            f"Career Readiness : {career['level']}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    # ==========================
    # Detected Skills
    # ==========================

    story.append(
        Paragraph("<b>Detected Skills</b>", styles["Heading2"])
    )

    for skill in detected_skills:
        story.append(
            Paragraph(f"• {skill}", styles["Normal"])
        )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    # ==========================
    # Missing Skills
    # ==========================

    story.append(
        Paragraph("<b>Missing Skills</b>", styles["Heading2"])
    )

    if missing_skills:

        for skill in missing_skills:
            story.append(
                Paragraph(f"• {skill}", styles["Normal"])
            )

    else:

        story.append(
            Paragraph("No Missing Skills 🎉", styles["Normal"])
        )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    # ==========================
    # Learning Roadmap
    # ==========================

    story.append(
        Paragraph("<b>Learning Roadmap</b>", styles["Heading2"])
    )

    for step in roadmap:

        story.append(
            Paragraph(
                f"Week {step['Week']} : {step['Skill']}",
                styles["Normal"]
            )
        )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )
    # ==========================
    # Resume Strengths
    # ==========================

    story.append(
        Paragraph("<b>Resume Strengths</b>", styles["Heading2"])
    )

    if review["strengths"]:

        for strength in review["strengths"]:

            story.append(
                Paragraph(f"• {strength}", styles["Normal"])
            )

    else:

        story.append(
            Paragraph("No strengths detected.", styles["Normal"])
        )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )

    # ==========================
    # Resume Suggestions
    # ==========================

    story.append(
        Paragraph("<b>Resume Suggestions</b>", styles["Heading2"])
    )

    if review["suggestions"]:

        for suggestion in review["suggestions"]:

            story.append(
                Paragraph(f"• {suggestion}", styles["Normal"])
            )

    else:

        story.append(
            Paragraph("No suggestions. Great Resume! 🎉", styles["Normal"])
        )

    story.append(
        Paragraph("<br/>", styles["Normal"])
    )
    # ==========================
    # Footer
    # ==========================

    story.append(
        Paragraph(
            "Generated by SkillPilot AI",
            styles["Heading3"]
        )
    )

    doc.build(story)